// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa42kZm4aTyfsN0o-3buCAq8j7ETiM__o',
    appId: '1:570753536392:web:cee3b914ca26808fde2a3d',
    messagingSenderId: '570753536392',
    projectId: 'fruit-hub-63815',
    authDomain: 'fruit-hub-63815.firebaseapp.com',
    storageBucket: 'fruit-hub-63815.appspot.com',
    measurementId: 'G-NM8THF6CFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAce9d50qakO6zF6Ju_gJDbwkvjcgDdITI',
    appId: '1:570753536392:android:b5102eef40f2d95ade2a3d',
    messagingSenderId: '570753536392',
    projectId: 'fruit-hub-63815',
    storageBucket: 'fruit-hub-63815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq8qEO57QTpZ45tJcTgcg8Gb-8rrfXW7g',
    appId: '1:570753536392:ios:c6f95a7f0659dd5fde2a3d',
    messagingSenderId: '570753536392',
    projectId: 'fruit-hub-63815',
    storageBucket: 'fruit-hub-63815.appspot.com',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq8qEO57QTpZ45tJcTgcg8Gb-8rrfXW7g',
    appId: '1:570753536392:ios:c6f95a7f0659dd5fde2a3d',
    messagingSenderId: '570753536392',
    projectId: 'fruit-hub-63815',
    storageBucket: 'fruit-hub-63815.appspot.com',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa42kZm4aTyfsN0o-3buCAq8j7ETiM__o',
    appId: '1:570753536392:web:dbf773f782b198a5de2a3d',
    messagingSenderId: '570753536392',
    projectId: 'fruit-hub-63815',
    authDomain: 'fruit-hub-63815.firebaseapp.com',
    storageBucket: 'fruit-hub-63815.appspot.com',
    measurementId: 'G-JDMMPNK6E2',
  );
}
